version: "3.6"
services:
  rabbitmq3:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=pavel_test
      - RABBITMQ_DEFAULT_PASS=pavel_test
    networks:
      - pika
    ports:
      - 15672:15672
      - 5672:5672
      - 5671:5671

  pykaldi_img_1:
    build:
      context: ./pykaldi
      target: pykaldi_img_1
    networks:
      - pika
    depends_on:
      - rabbitmq3
    ports:
      - 9000:9000
      
      
  pykaldi_img_2:
    build:
      context: ./pykaldi
      target: pykaldi_img_2
    networks:
      - pika
    depends_on:
      - rabbitmq3
    ports:
      - 9001:9001
      
networks:
  pika:
    attachable: true

