version: "3.6"
services:
  rabbitmq3:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=pavel_test
      - RABBITMQ_DEFAULT_PASS=pavel_test
    networks:
      - pika
    ports:
      - 15672:15672
      - 5672:5672
      - 5671:5671

  pykaldi:
    build: ./pykaldi
    container_name: 'pykaldi-rus-1'
    networks:
      - pika
    depends_on:
      - rabbitmq3
    ports:
      - 9000:9000
      
      
  pykaldi:
    build: ./pykaldi_2
    container_name: 'pykaldi-rus-2'
    networks:
      - pika
    depends_on:
      - rabbitmq3
    ports:
      - 9001:9001
      
networks:
  pika:
    attachable: true

